baseurl: '/'
permalink: pretty
title: 'Impress 2023 - Workshop on Learning and Evaluating Recommendations with Impressions'

google_analytics_id: ""

homepage:
  show_call_box: false
  show_social_buttons: true

logo:
  mobile: "images/recsys-logo.png"
  desktop: "images/recsys-logo.png"
  desktop_height: "36px"

seo:
  meta_og_title: "2023 Workshop on Learning and Evaluating Recommendations with Impressions"
  meta_og_type: "website"
  meta_og_url: "https://mauriziofd.github.io/impress2023"
  meta_og_description: "The Italian Information Retrieval Workshop (IIR) is a meeting forum stimulating and disseminating research in Information Retrieval, where Italian researchers (especially young ones) and researchers affiliated with Italian institutions can network and discuss their research results in an informal way."


collections:
  services:
    output: true
  editions:
    output: true
  team:
    output: true
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: info
      - name: Session
        color: warning
      - name: Breaks
        color: success
      - name: Closing
        color: danger

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
